os: osx
osx_image: xcode10.2
language: swift
script: xcodebuild clean build test -workspace Simplified.xcodeproj/project.xcworkspace -scheme "Simplified" -sdk iphonesimulator -destination "platform=iOS Simulator",OS=12.2,name="iPhone 8" ONLY_ACTIVE_ARCH=NO
